---
- hosts: "localhost"
  connection: "local"
  collections:
    - vmware.alb
  vars_files:
    - "generic.yml"

  tasks:
    - name: "Configure System"
      avi_systemconfiguration:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        api_version: "{{ avi_credentials.api_version }}"
        avi_api_update_method: patch
        avi_api_patch_op: replace
        portal_configuration:
          sslkeyandcertificate_refs:
            - "/api/sslkeyandcertificate/?name=Wildcard-ECDSA-Cert-Portal"
