---
- name: "Deploy vSphere Cloud"
  hosts: "localhost"
  connection: "local"
  vars_files:
    - "generic.yml"
  vars:
    usable_networks: []
    create_dns_provider: "{{ (dns_config.service_domains|default([]))|length>0 }}"

  tasks:
    - name: "Create Avi IPAM Provider"
      vmware.alb.avi_ipamdnsproviderprofile:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: '{{ "VMware-IPAM-" + cloud_parameters.name }}'
        type: "IPAMDNS_TYPE_INTERNAL"
        allocate_ip_in_vrf: false
      register: ipamprovider

    - name: "Create Avi DNS Provider"
      vmware.alb.avi_ipamdnsproviderprofile:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: '{{ "VMware-DNS-" + cloud_parameters.name }}'
        type: IPAMDNS_TYPE_INTERNAL_DNS
        internal_profile:
          dns_service_domain: "{{ dns_config.service_domains }}"
      when: create_dns_provider

    - name: "Create NSX-T cloud"
      vmware.alb.avi_cloud:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        dhcp_enabled: false
        ipam_provider_ref: "{{ ipamprovider.obj.url }}"
        dns_provider_ref: '{{ "/api/ipamdnsproviderprofile/?name=VMware-DNS-" + cloud_parameters.name if create_dns_provider else None }}'
        name: "nsxt"
        nsxt_configuration:
          automate_dfw_rules: false
          data_network_config:
            tier1_segment_config:
              manual:
                tier1_lrs:
                - segment_id: "/infra/segments/tenant1-se"
                  tier1_lr_id: "/infra/tier-1s/tenent1"
              segment_config_mode: "TIER1_SEGMENT_MANUAL"
            transport_zone: "/infra/sites/default/enforcement-points/default/transport-zones/1b3a2f36-bfd1-443e-a0f6-4de01abc963e"
            tz_type: "OVERLAY"
          management_network_config:
            overlay_segment:
              segment_id: "/infra/segments/avi-se"
              tier1_lr_id: "/infra/tier-1s/lab-mgmt"
            transport_zone: "/infra/sites/default/enforcement-points/default/transport-zones/1b3a2f36-bfd1-443e-a0f6-4de01abc963e"
            tz_type: "OVERLAY"
          nsxt_credentials_ref: "https://avi01a.vmlab.local/api/cloudconnectoruser/cloudconnectoruser-fda20e10-1a03-440f-b240-f4790a5cb172"
          nsxt_url: "192.168.11.21"
          site_id: "default"
          domain_id: "default"
          enforcementpoint_id: "default"
        obj_name_prefix: "nsx"
        prefer_static_routes: false
        vtype: "CLOUD_NSXT"
      register: cloud

    - name: "Wait for network sync for cloud to complete..."
      vmware.alb.avi_api_session:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        http_method: "get"
        path: "cloudruntime"
        params:
          name: "{{ cloud_parameters.name }}"
      register: cloudruntime
      until: cloudruntime.obj.results[0].network_sync_complete
      retries: 30
      delay: 5

    - name: "Configure cloud management network"
      vmware.alb.avi_cloud:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        avi_api_update_method: "patch"
        avi_api_patch_op: "replace"
        name: "{{ cloud_parameters.name }}"
        vcenter_configuration:
          management_ip_subnet: "{{ cloud_parameters.management_ip_subnet }}"
          management_network: '{{ "/api/vimgrnwruntime/?name=" + cloud_parameters.management_network }}'
        vtype: "CLOUD_VCENTER"

    - name: "Configure management default route"
      vmware.alb.avi_vrfcontext:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "management"
        cloud_ref: '{{ "/api/cloud/?name=" + cloud_parameters.name }}'
        static_routes:
          - next_hop:
              addr: "{{ cloud_parameters.management_gateway }}"
              type: "V4"
            prefix:
              ip_addr:
                addr: "0.0.0.0"
                type: "V4"
              mask: 0
            route_id: "1"

    - name: "Configure networks"
      vmware.alb.avi_network:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "{{ item.name }}"
        cloud_ref: '{{ "/api/cloud/?name=" + cloud_parameters.name }}'
        dhcp_enabled: false
        ip6_autocfg_enabled: false
        exclude_discovered_subnets: true
        configured_subnets:
          - prefix:
              ip_addr:
                addr: "{{ item.addr }}"
                type: "V4"
              mask: "{{ item.mask }}"
            static_ip_ranges: "{{ item.static_ip_ranges | default(omit) }}"
            static_ranges: "{{ item.static_ranges | default(omit) }}"
      loop: "{{ ipam_config }}"

    - name: "Collate usable subnets"
      ansible.builtin.set_fact:
        usable_networks: '{{ usable_networks + [{"nw_ref": "/api/network/?name=" + item.name}] }}'
      when: item.add_to_ipam
      loop: "{{ ipam_config }}"

    - name: "Add usable subnets to IPAM"
      vmware.alb.avi_api_session:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        http_method: "patch"
        path: '{{ "ipamdnsproviderprofile/" + ipamprovider.obj.uuid }}'
        data:
          replace:
            internal_profile:
              usable_networks: "{{ usable_networks }}"

