---
- hosts: "localhost"
  connection: "local"
  collections:
    - vmware.alb
  vars_files:
    - "generic.yml"
  tasks:
    - name: Example to create VrfContext object
      avi_cloudconnectoruser:
        avi_credentials: "{{ avi_credentials }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: SA-Infra-NS-ansible-1
        obj_password: test-password