---
- name: "Create starttls datascript"
  hosts: "localhost"
  connection: "local"
  vars_files:
    - "../../generic.yml"
  tasks:
    - name: "Create Datascript"
      vmware.alb.avi_vsdatascriptset:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        name: "starttls"
        datascript: 
          - evt: "VS_DATASCRIPT_EVT_L4_REQUEST"
            script: "{{lookup('file', './l4request.xml') }}"
          - evt: "VS_DATASCRIPT_EVT_L4_RESPONSE"
            script: "{{lookup('file', './l4response.xml') }}"
          - evt: "VS_DATASCRIPT_EVT_TCP_CLIENT_ACCEPT"
            script: "{{lookup('file', './accept.xml') }}"
          
